In [1]:
import pandas as pd
import numpy as np

Exercise 1: Load the Dataset

In [48]:
# Load diabets Dataset
diabets = pd.read_csv('diabetes.csv')
print("Dataset loaded successfully from URL!")

Dataset loaded successfully from URL!

In [49]:
print("the first five rows")
diabets.head()

the first five rows

,768,8,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1,6,148,72,35,0,33.6,0.627,50,1
2,1,85,66,29,0,26.6,0.351,31,0
3,8,183,64,0,0,23.3,0.672,32,1
4,1,89,66,23,94,28.1,0.167,21,0

In [50]:
print("the last five rows")
diabets.tail()

the last five rows

,768,8,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
764,10,101,76,48,180,32.9,0.171,63,0
765,2,122,70,27,0,36.8,0.34,27,0
766,5,121,72,23,112,26.2,0.245,30,0
767,1,126,60,0,0,30.1,0.349,47,1
768,1,93,70,31,0,30.4,0.315,23,0

In [51]:
print("shape of the dataset")
diabets.shape

shape of the dataset

(769, 9)

In [56]:
cleanedDiabets=diabets.iloc[1:]

In [57]:
cleanedDiabets = cleanedDiabets.rename(columns={
    '768': 'Pregnancies',
    '8': 'Glucose', 
    'Unnamed: 2': 'BloodPressure',
    'Unnamed: 3': 'SkinThickness',
    'Unnamed: 4': 'Insulin',
    'Unnamed: 5': 'BMI',
    'Unnamed: 6': 'DiabetesPedigreeFunction',
    'Unnamed: 7': 'Age',
    'Unnamed: 8': 'Outcome'
})

In [59]:
cleanedDiabets

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
2,1,85,66,29,0,26.6,0.351,31,0
3,8,183,64,0,0,23.3,0.672,32,1
4,1,89,66,23,94,28.1,0.167,21,0
5,0,137,40,35,168,43.1,2.288,33,1
6,5,116,74,0,0,25.6,0.201,30,0
...,...,...,...,...,...,...,...,...,...
764,10,101,76,48,180,32.9,0.171,63,0
765,2,122,70,27,0,36.8,0.34,27,0
766,5,121,72,23,112,26.2,0.245,30,0
767,1,126,60,0,0,30.1,0.349,47,1
768,1,93,70,31,0,30.4,0.315,23,0

Exercise 2: Explore the Dataset

In [ ]:
1. How many rows are there?
   - 767
2. How many columns?
    - 9
3. What are the feature names?
  - ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']
4. Which column is the target variable?
 - outcome
5. What are the data types?
 - all are object datatypes
6. Are there missing values?
 - no missing value

In [ ]:
7. Display statistical summary.

In [60]:
cleanedDiabets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 2 to 768
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               767 non-null    object
 1   Glucose                   767 non-null    object
 2   BloodPressure             767 non-null    object
 3   SkinThickness             767 non-null    object
 4   Insulin                   767 non-null    object
 5   BMI                       767 non-null    object
 6   DiabetesPedigreeFunction  767 non-null    object
 7   Age                       767 non-null    object
 8   Outcome                   767 non-null    object
dtypes: object(9)
memory usage: 54.1+ KB

In [61]:
cleanedDiabets.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,767,767,767,767,767,767,767,767,767
unique,17,136,47,51,186,248,516,52,2
top,1,100,70,0,0,32,0.254,22,0
freq,135,17,57,227,373,13,6,72,500

In [62]:
cleanedDiabets.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

Exercise 3: Data Cleaning

In [63]:
# Part A : Check if there are any duplicate rows and removing them
duplicateRows = cleanedDiabets.duplicated()
print(f"Number of duplicate rows: {duplicateRows.sum()}")
print(f"Duplicate rows exist: {duplicateRows.any()}")

Number of duplicate rows: 0
Duplicate rows exist: False

In [64]:
# Part B : checking if there are 0 values
print (" there are no zero values in the selected columns")
# List of columns to check
checkColumns= ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

# Count zero values in each column
for column in checkColumns:
    zero_count = (cleanedDiabets[column] == 0).sum()
    print(f"{column}: {zero_count} zero values")

 there are no zero values in the selected columns
Glucose: 0 zero values
BloodPressure: 0 zero values
SkinThickness: 0 zero values
Insulin: 0 zero values
BMI: 0 zero values

In [47]:

# Part C - First convert string columns to numeric, then replace 0 with NaN
diabets = diabets.apply(pd.to_numeric, errors='coerce')  # Convert strings to numbers
diabets = diabets.replace(0, np.nan)

# Part D - Replace missing values using the median of each column
diabets = diabets.fillna(diabets.median())