In [1]:
import pandas as pd

In [5]:
# student table
students = pd.DataFrame({ 
"Student_ID": [1, 2, 3, 4], 
"Student_Name": ["Abel", "Sara", "John", "Helen"] 
})
students

   Student_ID Student_Name
0           1         Abel
1           2         Sara
2           3         John
3           4        Helen

In [6]:
# Enrollments table
enrollments = pd.DataFrame({ 
"Student_ID": [1, 2, 5], 
"Course": ["Python", "SQL", "Machine Learning"] 
})
enrollments

   Student_ID            Course
0           1            Python
1           2               SQL
2           5  Machine Learning

In [10]:
# inner join
result = pd.merge(
    students ,
    enrollments,
    on="Student_ID",
    how="inner"
)
result

   Student_ID Student_Name  Course
0           1         Abel  Python
1           2         Sara     SQL

In [12]:
# left join
result=pd.merge(
    students,
    enrollments,
    on = "Student_ID",
    how ="left"
)
result

   Student_ID Student_Name  Course
0           1         Abel  Python
1           2         Sara     SQL
2           3         John     NaN
3           4        Helen     NaN

In [13]:
# right join
result = pd.merge( 
students, 
enrollments, 
on="Student_ID", 
how="right" 
)
result

   Student_ID Student_Name            Course
0           1         Abel            Python
1           2         Sara               SQL
2           5          NaN  Machine Learning

In [18]:
# outer join 
result = pd.merge( 
students, 
enrollments, 
on="Student_ID", 
how="outer" 
) 
result

   Student_ID Student_Name            Course
0           1         Abel            Python
1           2         Sara               SQL
2           3         John               NaN
3           4        Helen               NaN
4           5          NaN  Machine Learning

In [19]:
result["Course"] = result["Course"].fillna("Not Enrolled") 
result["Student_Name"] = result["Student_Name"].fillna("unknown") 
result

   Student_ID Student_Name            Course
0           1         Abel            Python
1           2         Sara               SQL
2           3         John      Not Enrolled
3           4        Helen      Not Enrolled
4           5      unknown  Machine Learning